config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }, presence: true

  def self.categories
    ["chinese", "italian", "japanese", "french", "belgian"]
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true, inclusion: { in: (0..5) }, numericality: {only_integer: true}
  validates :content, presence: true

  def self.average_rating(reviews)
    return 0 if reviews.empty?

    total_rating = reviews.sum(&:rating)
    (total_rating.to_f / reviews.size).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show]


  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.valid?
      @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = @restaurant.reviews
  end

  # def new
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.valid?
      @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>List of all the Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <h4>Location: <%= restaurant.address %></h4>
  <h4>The restaurant has an <%= restaurant.category %> cuisine</h4>
  <% if restaurant.phone_number %>
    <h4>Phone Number: <%= restaurant.phone_number %></h4>
  <% end  %>
  <h4>The restaurant has: <%= restaurant.reviews.count %> Reviews</h4>

  <%= link_to "Go to restaurant", restaurant_path(restaurant) %>
<% end %>

<%= link_to "Create a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: Restaurant.categories %>
  <%= f.input :phone_number %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<h4>Location: <%= @restaurant.address %></h4>
<h4>The restaurant has an <%= @restaurant.category %> cuisine</h4>
<% if @restaurant.phone_number %>
  <h4>Phone Number: <%= @restaurant.phone_number %></h4>
<% end  %>
<h4>The restaurant has: <%= @restaurant.reviews.count %> Reviews</h4>

<%= link_to "Back to Homepage", restaurants_path %><br>
<%= link_to "See reviews", restaurant_reviews_path(@restaurant) %><br>
<br>


<h2>Write a Review:</h2>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/reviews/index.html.erb
<h2>Reviews:</h2>
<h3> Average Rating: <%= @reviews.average_rating(@reviews) %>/5 </h3>

<ul>
  <% @reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %><br> The Rating is: <%= review.rating %></li>
  <% end %>
</ul>

<%= link_to "Go back", restaurant_path(@restaurant) %>